name: 01-building-blocks

on: push

jobs:
    echo:
      runs-on: ubuntu-Latest
      steps: 
        - name: print name
          run: |
            echo "hello world"
            echo "this is my first github action"


      
