name: 02-event-blocks

on: 
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '* * * * *'

jobs:
    echo:
        runs-on: ubuntu-Latest
        steps:
            - name: print event
              run: |
               echo "event is ${{github.event_name}}"